  [build-system]                                                                                                                                                                                                                                             
  requires = ["setuptools"]                                                                                                                                                                                                                                
  build-backend = "setuptools.build_meta"                                                                                                                                                                                                                  

  [tool.setuptools.package-dir]                                                                                                                                                                                                                              
  "ksef_cli" = "ksef_cli"
                                                                                                                                                                                                                                                             
  [tool.setuptools.package-data]                                                                                                                                                                                                                           
  "ksef_cli" = ["help.txt"]                                                                                                                                                                                                                                

  [project.urls]
  Repository = "https://github.com/stanislawbartkowski/ksef_cli"
  Changelog = "https://github.com/stanislawbartkowski/ksef_cli/blob/main/release.md"
  
  [project]
  name = "ksef2.0_cli"
  version = "1.2.0"
  description= "A command-line tool for interacting with KSeF 2.0 (Krajowy System e-Faktur), Poland's national electronic invoicing platform"
  requires-python = ">=3.10"
  authors = [
    {name = "Stanisław Bartkowski", email = "stanislawbartkowski@gmail.com"},                                                                                                                                                                              
  ]                                                                                                                                                                                                                                                          
  dependencies = [
    "ksef2.0-python",
    "pyyaml",
    "python-dateutil"
  ]                                                                                                                                                                                                                                                        
  readme = "README.md"

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["tests"]
python_files = ["test*.py"]

[tool.ruff]
line-length = 120
exclude = [".venv"]
